services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    container_name: cinema_mongodb
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - ./mongo:/data/db
